# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ImageMessages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13ImageMessages.proto\x12\rImageMessages\"\x85\x01\n\x08\x41SIimage\x12\x0e\n\x06header\x18\x01 \x02(\x0f\x12\n\n\x02id\x18\x02 \x02(\x0f\x12\x19\n\x11messageByteLength\x18\x03 \x02(\x0f\x12\x10\n\x08\x62itDepth\x18\x04 \x02(\x0f\x12\r\n\x05width\x18\x05 \x02(\x0f\x12\x0e\n\x06height\x18\x06 \x02(\x0f\x12\x11\n\timageData\x18\x07 \x01(\x0c\"j\n\x0e\x41SIctrlMessage\x12\x0e\n\x06header\x18\x01 \x02(\x0f\x12\n\n\x02id\x18\x02 \x02(\x0f\x12\x19\n\x11messageByteLenght\x18\x03 \x02(\x0f\x12\x0f\n\x07\x62inning\x18\x04 \x02(\x0f\x12\x10\n\x08\x65xposure\x18\x05 \x02(\x0f\"p\n\x12stepperCtrlMessage\x12\x0e\n\x06header\x18\x01 \x02(\x0f\x12\n\n\x02id\x18\x02 \x02(\x0f\x12\x0c\n\x04\x61xis\x18\x03 \x02(\t\x12\x11\n\tcmdString\x18\x06 \x02(\t\x12\x0e\n\x06\x63ounts\x18\x04 \x01(\x0f\x12\r\n\x05speed\x18\x05 \x01(\x0f')



_ASIIMAGE = DESCRIPTOR.message_types_by_name['ASIimage']
_ASICTRLMESSAGE = DESCRIPTOR.message_types_by_name['ASIctrlMessage']
_STEPPERCTRLMESSAGE = DESCRIPTOR.message_types_by_name['stepperCtrlMessage']
ASIimage = _reflection.GeneratedProtocolMessageType('ASIimage', (_message.Message,), {
  'DESCRIPTOR' : _ASIIMAGE,
  '__module__' : 'ImageMessages_pb2'
  # @@protoc_insertion_point(class_scope:ImageMessages.ASIimage)
  })
_sym_db.RegisterMessage(ASIimage)

ASIctrlMessage = _reflection.GeneratedProtocolMessageType('ASIctrlMessage', (_message.Message,), {
  'DESCRIPTOR' : _ASICTRLMESSAGE,
  '__module__' : 'ImageMessages_pb2'
  # @@protoc_insertion_point(class_scope:ImageMessages.ASIctrlMessage)
  })
_sym_db.RegisterMessage(ASIctrlMessage)

stepperCtrlMessage = _reflection.GeneratedProtocolMessageType('stepperCtrlMessage', (_message.Message,), {
  'DESCRIPTOR' : _STEPPERCTRLMESSAGE,
  '__module__' : 'ImageMessages_pb2'
  # @@protoc_insertion_point(class_scope:ImageMessages.stepperCtrlMessage)
  })
_sym_db.RegisterMessage(stepperCtrlMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ASIIMAGE._serialized_start=39
  _ASIIMAGE._serialized_end=172
  _ASICTRLMESSAGE._serialized_start=174
  _ASICTRLMESSAGE._serialized_end=280
  _STEPPERCTRLMESSAGE._serialized_start=282
  _STEPPERCTRLMESSAGE._serialized_end=394
# @@protoc_insertion_point(module_scope)
